const MIN_MOVEMENT_DELAY = 1000;
const MAX_MOVEMENT_DELAY = 10000;
const MOVEMENTS_REQUEST_DELAY = 5000;
const MIN_STEP_VALUE = 0.0001;
const MAX_STEP_VALUE = 0.0005;

export {
  MIN_MOVEMENT_DELAY, MAX_MOVEMENT_DELAY, MOVEMENTS_REQUEST_DELAY, MIN_STEP_VALUE, MAX_STEP_VALUE,
};
